declare module 'user-server' {
    /**
    * Role of the user
    * @type {'admin' | 'customer'}
    */
    export type role = 'admin' | 'customer'
    /**
    * Country of the user
    * @type {'Russia' | 'Belarus' | 'Kazakhstan'}
    */
    export type country = 'Russia' | 'Belarus' | 'Kazakhstan'
    /**
     * Notification set.
     * @interface iuser
     */
    export type notification = {
        notificationOrdersStatus: boolean;
        notificationCommentsStatus: boolean;
        notificationMessagesFromAdminStatus: boolean;
        notificationNewItemsStatus: boolean;
    };
    /**
     * Interface representing the guest.
     * @interface iuser
     */
    export interface iuser {
        /**
         * Identifier generated by uuidv4() for anonymous users.
         * @type {string}
         */
        _id: object
        /**
         * User role, can be either 'admin' or 'customer'.
         * @type {role}
         */
        role: role
    }
    /**
     * Interface representing an registered user.
     * @interface iuserExtend
     * @extends {iuser}
     */
    export interface iuserExtend extends iuser{
        /**
         * Email of the user.
         * @type {string}
         */
        email: string
        /**
         * Full name of the user.
         * @type {string}
         */
        fullName: string,
        /**
         * Phone of the user.
         * @type {string}
         */
        phoneNumber: string
        /**
         * Notifications of the user.
         * @type {string}
         */
        notifications: notification
        /**
         * Country of the user, optional and restricted to specific values.
         * @type {country | undefined}
         */
        country?: country,
        /**
         * Address of the user, optional.
         * @type {string | undefined}
         */
        address?: string,
        /**
         * Postal code of the user's address, optional.
         * @type {number | undefined}
         */
        postCode?: number
    }
}